Done task2
htmlacademy-javascript/2125091-kekstagram-26 pull request #3
Opened 2022-06-09 14:38 UTC by BalSerg

2022-06-09 15:19 UTC, KletskovG requested changes

2022-06-09 15:19 UTC, KletskovG commented on index.html
> +  <script src="js/main.js"></script>
Это не будет работать. Скрипты можно добавлять только в body. Так же желательно добавлять их именно в конец body, для оптимизации загрузке

2022-06-09 15:19 UTC, KletskovG commented on js/main.js
> +  if((endInterval > startInterval) && (startInterval !== 0) && (endInterval !== 0)) {
Проверки на то, что числа будут положительными не нужны. По условию задачи сказано, что они могут быть от нуля. То есть это уже в косыми задачи заложено

2022-06-09 15:19 UTC, KletskovG commented on js/main.js
> +    console.log(Math.floor(Math.random() * (endInterval - startInterval + 1) + startInterval));
Функция должна возвращать результат через return, как это сделано у тебя во второй функции

2022-06-09 15:19 UTC, KletskovG commented on js/main.js
> +  yourString = String(yourString);
Эти два преобразования не нужны. Так как в условии задачи отражено, первый аргумент - это строка, а второй - это число. Так что эти две строки на самом деле не нужны

2022-06-09 20:04 UTC, BalSerg commented on index.html
> +  <script src="js/main.js"></script>
<script> перенёс

2022-06-09 20:04 UTC, BalSerg commented on js/main.js
> +  if((endInterval > startInterval) && (startInterval !== 0) && (endInterval !== 0)) {
Убрал лишние проверки

2022-06-09 20:05 UTC, BalSerg commented on js/main.js
> +  yourString = String(yourString);
Убрал лишние преобразования

2022-06-10 04:32 UTC, KletskovG approved these changes

2022-06-10 04:32 UTC, merged